export default [
    {
      id: "doc1",
      title: "Dirección de Evaluación de Tecnologías Sanitarias - IETSI",
      content: "La Dirección de Evaluación de Tecnologías Sanitarias (DETS) del IETSI es el órgano encargado de realizar análisis sistemáticos y rigurosos sobre las tecnologías en salud que podrían implementarse o ya están siendo utilizadas en EsSalud. Estas tecnologías incluyen medicamentos, procedimientos médicos, equipos biomédicos, y estrategias organizacionales para la atención sanitaria.\n\nLa DETS aplica metodologías basadas en evidencia científica para determinar la efectividad, seguridad, eficiencia y viabilidad presupuestal de las tecnologías. El objetivo central es garantizar que los recursos institucionales se utilicen de forma óptima, priorizando aquellas tecnologías que aportan mayor valor en salud para los asegurados.\n\nUno de los productos más relevantes de esta dirección son los Informes de Evaluación de Tecnologías Sanitarias (IETS), que se elaboran para fundamentar técnicamente decisiones como la incorporación de un nuevo medicamento al Petitorio Farmacológico Institucional (PFI), la adopción de un dispositivo médico o la modificación de guías clínicas. Estos informes no solo recopilan datos internacionales, sino que contextualizan la evidencia al marco epidemiológico, económico y organizativo del sistema de salud peruano.\n\nAdemás, la DETS coordina procesos de reevaluación periódica, en los cuales tecnologías previamente aprobadas son revisadas para confirmar que su uso sigue siendo pertinente y coste-efectivo. Esto garantiza la actualización permanente del arsenal terapéutico institucional.\n\nLa dirección también representa a EsSalud en redes internacionales como RedETSA (Red de Evaluación de Tecnologías en Salud de las Américas), colaborando con agencias similares en otros países para compartir metodologías y experiencias. Gracias a esta colaboración y al desarrollo técnico de sus informes, la DETS ha sido reconocida por su contribución a la gestión basada en evidencia dentro del sistema público de salud peruano.",
      metadata: {
        source: "IETSI - EsSalud",
        category: "Evaluación de tecnologías",
        date: "2024-08-05"
      }
    },
    {
      id: "doc2",
      title: "Dirección de Investigación en Salud - IETSI",
      content: "La Dirección de Investigación en Salud (DIS) del IETSI tiene como propósito central fomentar una cultura investigativa en el ámbito del Seguro Social de Salud. Su responsabilidad abarca la promoción, regulación, financiamiento y monitoreo de investigaciones científicas que respondan a las prioridades sanitarias del país y de EsSalud.\n\nLa DIS diseña y gestiona convocatorias para financiar proyectos de investigación desarrollados por profesionales de la salud en hospitales, institutos especializados y redes asistenciales. Estas convocatorias promueven el estudio de enfermedades prevalentes, evaluación de servicios de salud, impacto de intervenciones médicas, salud ocupacional y calidad de vida, entre otros temas relevantes.\n\nPara garantizar la integridad ética y científica de las investigaciones, esta dirección también regula el funcionamiento de los Comités Institucionales de Ética en Investigación (CIEI). Los comités revisan protocolos, aseguran la protección de los derechos de los participantes, y vigilan el cumplimiento de normativas nacionales e internacionales.\n\nAdemás, la DIS ha implementado herramientas digitales como la Plataforma de Registro de Proyectos de Investigación (PRPI), donde se registran, aprueban y hacen seguimiento a los estudios. Esta plataforma permite transparentar el proceso investigativo y facilita la trazabilidad de los resultados.\n\nA través de convenios con universidades, centros académicos y organismos multilaterales, la DIS promueve la capacitación continua de investigadores, fortaleciendo competencias en bioestadística, diseño de estudios, publicación científica y uso ético de datos.\n\nEntre 2020 y 2024, la dirección ha cofinanciado más de 150 proyectos y ha contribuido a que EsSalud incremente su presencia en revistas científicas indexadas. Su producción científica se ha convertido en insumo clave para mejorar la toma de decisiones clínicas y administrativas.",
      metadata: {
        source: "IETSI - EsSalud",
        category: "Investigación científica",
        date: "2024-08-05"
      }
    },
    {
      id: "doc3",
      title: "Dirección de Guías de Práctica Clínica, Farmacovigilancia y Tecnovigilancia - IETSI",
      content: "La Dirección de Guías de Práctica Clínica, Farmacovigilancia y Tecnovigilancia (DGPCFT) es una de las áreas estratégicas del IETSI. Su misión es garantizar que las decisiones clínicas y el uso de productos sanitarios en EsSalud se basen en la mejor evidencia científica disponible, maximizando la seguridad del paciente y la efectividad terapéutica.\n\nEn el ámbito de las Guías de Práctica Clínica (GPC), esta dirección lidera procesos de elaboración, revisión y actualización de documentos normativos que orientan la atención médica en todas las redes de salud de EsSalud. Las guías son desarrolladas por grupos de trabajo interdisciplinarios y se validan a través de procesos de revisión externa y consulta pública. Están alineadas con estándares internacionales y adaptadas a la realidad epidemiológica y de recursos del país.\n\nRespecto a farmacovigilancia, la DGPCFT implementa y coordina un sistema nacional de vigilancia de reacciones adversas a medicamentos (RAM). Este sistema se basa en la notificación activa y pasiva desde los establecimientos de salud, y genera reportes técnicos que permiten adoptar medidas correctivas, actualizar alertas sanitarias y ajustar protocolos de uso de medicamentos.\n\nEn el campo de la tecnovigilancia, la dirección se encarga de monitorear los eventos adversos y fallas técnicas relacionados con dispositivos médicos y equipos biomédicos. Se realizan investigaciones de campo, análisis de riesgo y se implementan planes de acción en coordinación con áreas técnicas y proveedores.\n\nLa DGPCFT también promueve la cultura de la seguridad del paciente mediante la formación de personal médico y farmacéutico, campañas de sensibilización y desarrollo de materiales educativos. Además, participa activamente en redes como la UMC (Unidad de Monitoreo de la OMS) y en grupos técnicos nacionales junto a DIGEMID.\n\nGracias a sus esfuerzos, la dirección ha sido galardonada por iniciativas como la mejora del acceso a medicamentos innovadores y la implementación de sistemas de alerta temprana para prevenir daños asociados a tecnologías sanitarias en el sistema de salud.",
      metadata: {
        source: "IETSI - EsSalud",
        category: "Práctica clínica y vigilancia",
        date: "2024-08-05"
      }
    }
  ];
  