export default [
    {
        id: "doc1",
        title: "Guía de Práctica Clínica para el manejo de la Crisis Asmática en niños y adolescentes",
        content: "La Guía de Práctica Clínica (GPC) para el manejo de la crisis asmática en niños y adolescentes, aprobada por Resolución No 1015-IETSI-ESSALUD-2023, tiene como objetivo estandarizar el manejo clínico de esta condición en el ámbito de EsSalud. Esta guía fue elaborada por un grupo multidisciplinario conformado por pediatras, neumólogos, metodólogos y otros profesionales de salud del IETSI.\n\nLa GPC incluye recomendaciones basadas en evidencia para la evaluación inicial, tratamiento de primera y segunda línea, y alta hospitalaria. Se establecen recomendaciones específicas según la severidad de la crisis asmática (leve, moderada, severa y de riesgo vital), utilizando herramientas como el Pulmonary Score y la saturación de oxígeno. Las intervenciones educativas al alta también son destacadas como componente clave.\n\nEntre las recomendaciones clínicas se incluyen:\n- Uso del inhalador de dosis medida con espaciador en lugar de nebulización para administrar agonistas β2.\n- Preferencia por corticoides sistémicos frente a los inhalados, especialmente en crisis moderadas o severas.\n- Inclusión de anticolinérgicos como el bromuro de ipratropio en casos severos o de mala respuesta.\n- Uso de sulfato de magnesio como tratamiento de segunda línea si no hay respuesta al tratamiento inicial.\n\nSe otorgaron 12 recomendaciones (1 fuerte y 11 condicionales), 29 buenas prácticas clínicas (BPC) y 1 flujograma.\n\nLa guía está dirigida a médicos generales, pediatras, neumólogos, emergenciólogos, residentes y personal de enfermería y técnico. Tiene una vigencia de cinco años, con mecanismos establecidos para su revisión y actualización basada en nueva evidencia.\n\nAdemás, se incorpora un componente educativo al alta, incluyendo un plan de acción, evaluación de técnica inhalatoria, factores de riesgo, y seguimiento ambulatorio a las 72 horas.\n\nEl documento fue financiado por el IETSI y su versión extensa puede ser consultada en la web institucional de EsSalud.",
        metadata: {
            source: "IETSI - EsSalud",
            category: "Guías de práctica clínica",
            date: "2023-12-29"
        }
    },
    {
        id: "doc2",
        title: "Guía de Práctica Clínica para el Diagnóstico y Seguimiento de la Hipertensión Arterial Pulmonar",
        content: "La presente guía de práctica clínica (GPC) ha sido elaborada por el Instituto de Evaluación de Tecnologías en Salud e Investigación (IETSI) de EsSalud para estandarizar el diagnóstico y seguimiento de la hipertensión arterial pulmonar (HAP), una condición progresiva y potencialmente mortal. Esta guía, aprobada mediante Resolución N° 000056-IETSI-ESSALUD-2024, se basa en la metodología GRADE, evidencia científica rigurosa, y el consenso de expertos nacionales e internacionales.\n\nLa GPC incluye versiones extensa, corta y anexos, y ha sido desarrollada por un grupo multidisciplinario de cardiólogos, intensivistas, metodólogos y coordinadores del IETSI y de instituciones públicas y privadas, incluyendo especialistas de Colombia como revisores clínicos externos. La guía está dirigida a todo el personal de salud que interviene en la atención de pacientes con HAP en el tercer nivel de atención de EsSalud.\n\nAborda cinco preguntas clínicas clave relacionadas con el diagnóstico y seguimiento de la HAP, incluyendo: criterios ecocardiográficos de tamizaje, uso de nuevas definiciones hemodinámicas, escalas de estratificación del riesgo de mortalidad, parámetros ecocardiográficos relevantes para seguimiento y evaluación de tratamiento, y puntos de corte para el test de caminata de 6 minutos.\n\nEntre sus principales recomendaciones, se sugiere el uso de la velocidad de regurgitación tricuspídea (TRVmax ≥2.9 m/s) más signos ecocardiográficos indirectos para tamizaje, la adopción del nuevo umbral de presión pulmonar media (>20 mmHg), y el empleo de escalas de riesgo de tres y cuatro niveles según la guía ESC/ERS 2022. Asimismo, se detallan parámetros pronósticos como TAPSE, RVLS y RVEF, y se recomienda la caminata de 6 minutos como instrumento de seguimiento.\n\nEsta guía tiene una vigencia de cinco años y será actualizada según evidencia futura. Refuerza la atención basada en evidencia, fomenta la equidad, y promueve la sostenibilidad del sistema mediante la toma de decisiones clínicas estandarizadas y costo-efectivas.",
        metadata: {
            source: "IETSI - EsSalud",
            category: "Guías de práctica clínica",
            date: "2024-12-13"
        }
    }
];
